name: FTP upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download frontend dependencies
        run: npm install

      - name: Build frontend with NPM
        run: npm run build

      - name: List output files
        run: find dist/front-end/ -print

      - name: Upload build
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/front-end/
          server-dir: habito/
